#!/bin/sh
# deploy_tinyproxy.sh — RC400L tinyproxy HTTP/HTTPS proxy deployer
# Requires: rootshell access via adb
#
# SETUP (from PC — run from repo root):
#   MSYS_NO_PATHCONV=1 adb push PortableApps/05_tinyproxy /data/tmp/tinyproxy
#   adb shell
#   rootshell
#   sh /data/tmp/tinyproxy/deploy_tinyproxy.sh
#
# WHAT THIS DOES:
#   1. Copies tinyproxy binary to /cache/bin/tinyproxy (root-owned, executable)
#   2. Writes /cache/tinyproxy.conf (Listen 192.168.1.1, Port 8118)
#   3. Injects a `once` inittab entry so init spawns tinyproxy with full caps
#      (rootshell CapBnd=0x00c0 lacks CAP_NET_BIND_SERVICE; init has full caps)
#   4. Signals init (kill -HUP 1) to spawn tinyproxy
#   5. Verifies process started and port 8118 is listening
#   6. Restores /etc/inittab and cleans up /data/tmp staging
#
# AFTER INSTALL — configure WiFi clients:
#   Set HTTP proxy to:  192.168.1.1 : 8118
#   This proxies both HTTP and HTTPS (CONNECT tunnel) through the Orbic LTE link.
#
# MANAGE:
#   Stop:    kill $(cat /cache/tinyproxy.pid)
#   Log:     cat /cache/tinyproxy.log
#   Restart: Re-run this script
#
# OPTIONAL — transparent proxy via iptables (requires deploy_xtables.sh first):
#   Redirect all WiFi client port 80 traffic through tinyproxy:
#     sh /cache/ipt/ipt_ctl.sh iptables -t nat -A ORBIC_PREROUTING \
#         -i bridge0 -p tcp --dport 80 ! -d 192.168.1.1 \
#         -j REDIRECT --to-ports 8118
#   Note: transparent HTTPS (port 443) requires TPROXY and is not
#         supported by REDIRECT target without client cooperation.
#   To remove:
#     sh /cache/ipt/ipt_ctl.sh iptables -t nat -D ORBIC_PREROUTING \
#         -i bridge0 -p tcp --dport 80 ! -d 192.168.1.1 \
#         -j REDIRECT --to-ports 8118
#
# WHY INITTAB ESCAPE:
#   rootshell runs uid=0 but CapBnd=0x00c0 (CAP_SETUID + CAP_SETGID only).
#   The Qualcomm LSM blocks socket() for the entire adb process tree
#   (adbd -> adb shell -> rootshell), so tinyproxy spawned directly from
#   rootshell cannot bind any port. init (PID 1) has CapBnd=0x3fffffffff.
#   Injecting a `once` entry and sending kill -HUP 1 causes init to spawn
#   tinyproxy outside the adbd LSM context, allowing socket binding.

SRC_DIR="/data/tmp/tinyproxy"
TINYPROXY_SRC="$SRC_DIR/tinyproxy"
TINYPROXY_BIN="/cache/bin/tinyproxy"
CONF_FILE="/cache/tinyproxy.conf"
LOG_FILE="/cache/tinyproxy.log"
PID_FILE="/cache/tinyproxy.pid"
LISTEN_IP="192.168.1.1"
PORT="8118"
INITTAB="/etc/inittab"
INITTAB_BAK="/data/tmp/inittab.tprox.bak"

# Unique 4-char tag for inittab id field (busybox limit)
TAG="tp$(( ($$ % 9) + 1 ))$(date +%S 2>/dev/null | cut -c3 || echo 0)"

ok()   { echo "  [+] $*"; }
info() { echo "  [*] $*"; }
err()  { echo "  [!] $*"; }
hdr()  { echo ""; echo "=== $* ==="; }

echo ""
echo "========================================"
echo " RC400L tinyproxy HTTP/HTTPS deployer"
echo "========================================"
echo " listen   : $LISTEN_IP:$PORT"
echo " conf     : $CONF_FILE"
echo " log      : $LOG_FILE"
echo " pid      : $PID_FILE"
echo " tag      : $TAG"
echo ""

# -------------------------------------------------------------------------
# [1] Preflight checks
# -------------------------------------------------------------------------
hdr "1. Preflight"

if [ "$(id -u)" != "0" ]; then
    err "Not running as root. Run: rootshell, then re-run this script."
    exit 1
fi
ok "Running as root (uid=$(id -u))"

if [ ! -f "$TINYPROXY_SRC" ]; then
    err "Binary not found: $TINYPROXY_SRC"
    err "Push from PC first:"
    err "  MSYS_NO_PATHCONV=1 adb push PortableApps/05_tinyproxy /data/tmp/tinyproxy"
    exit 1
fi
ok "Source binary present: $TINYPROXY_SRC"

# Stop any existing tinyproxy instance
if [ -f "$PID_FILE" ]; then
    OLDPID=$(cat "$PID_FILE" 2>/dev/null)
    if [ -n "$OLDPID" ] && [ -d "/proc/$OLDPID" ]; then
        info "tinyproxy already running (PID=$OLDPID). Stopping it first..."
        kill "$OLDPID" 2>/dev/null
        sleep 1
        ok "Stopped existing instance"
    fi
    rm -f "$PID_FILE"
fi

# -------------------------------------------------------------------------
# [2] Install binary
# -------------------------------------------------------------------------
hdr "2. Installing tinyproxy binary"

mkdir -p /cache/bin || { err "mkdir /cache/bin failed"; exit 1; }
cp "$TINYPROXY_SRC" "$TINYPROXY_BIN" || { err "cp tinyproxy failed — check source exists"; exit 1; }
chmod 755 "$TINYPROXY_BIN"           || { err "chmod tinyproxy failed"; exit 1; }
ok "Installed: $(ls -la $TINYPROXY_BIN)"

# -------------------------------------------------------------------------
# [3] Write tinyproxy configuration
# -------------------------------------------------------------------------
hdr "3. Writing $CONF_FILE"

cat > "$CONF_FILE" << CONF
# tinyproxy.conf — RC400L / Orbic hotspot
# Generated by deploy_tinyproxy.sh

# Listening address and port
# Only bind on the WiFi LAN interface IP, not on rmnet0 (LTE).
Listen ${LISTEN_IP}
Port ${PORT}

# Connection timeout in seconds
Timeout 90

# Log file (use syslog-style if path not writable, but /cache is writable)
LogFile ${LOG_FILE}

# Verbosity: 0=Critical 1=Error 2=Warning 3=Notice 4=Connect 5=Info
LogLevel Connect

# PID file
PidFile ${PID_FILE}

# Maximum simultaneous client connections
MaxClients 100

# Minimum and maximum spare server processes (tinyproxy is single-process,
# these control the pre-fork pool — keep low for embedded target)
MinSpareServers 2
MaxSpareServers 5

# Allow connections only from the WiFi client subnet
Allow 192.168.1.0/24

# Remove the Via header (reduces proxy fingerprint)
DisableViaHeader Yes

# Do NOT act as a reverse proxy
# (no ReverseProxy entries)

# User/Group — tinyproxy usually drops privs after binding.
# Leave unset so it runs as root (init-spawned), which is fine here
# since it only listens on the LAN-side IP anyway.
# User nobody
# Group nogroup
CONF

ok "Config written: $CONF_FILE"
info "Key settings:"
grep -E "^(Listen|Port|Timeout|MaxClients|Allow|DisableVia)" "$CONF_FILE" | sed 's/^/      /'

# -------------------------------------------------------------------------
# [4] Backup /etc/inittab
# -------------------------------------------------------------------------
hdr "4. Backing up /etc/inittab"

if [ ! -f "$INITTAB_BAK" ]; then
    cp "$INITTAB" "$INITTAB_BAK" || { err "inittab backup failed"; exit 1; }
    ok "Backed up to $INITTAB_BAK"
else
    ok "Existing backup at $INITTAB_BAK (not overwriting)"
fi

# -------------------------------------------------------------------------
# [5] Inject inittab once entry
# -------------------------------------------------------------------------
hdr "5. Injecting inittab once entry"

# Remove any stale tinyproxy entries (tag starts with "tp")
grep -v "^tp[0-9]" "$INITTAB" > /data/tmp/inittab.tprox.new 2>/dev/null
cp /data/tmp/inittab.tprox.new "$INITTAB"
rm -f /data/tmp/inittab.tprox.new

# tinyproxy daemonizes by default when given a config file.
# The `once` action in inittab fires once; tinyproxy then detaches and
# manages itself. The PID file lets us track and stop it later.
TINYPROXY_CMD="$TINYPROXY_BIN -c $CONF_FILE"

echo "${TAG}:5:once:${TINYPROXY_CMD}" >> "$INITTAB"
ok "Entry appended: ${TAG}:5:once:${TINYPROXY_CMD}"

if ! grep -q "^${TAG}" "$INITTAB"; then
    err "Entry not confirmed in /etc/inittab — possible read-only filesystem"
    exit 1
fi
ok "Entry confirmed in /etc/inittab"

# -------------------------------------------------------------------------
# [6] Signal init to spawn tinyproxy
# -------------------------------------------------------------------------
hdr "6. Signaling init (kill -HUP 1)"

kill -HUP 1
info "Waiting for tinyproxy to start (up to 15s)..."

TPID=""
for i in $(seq 1 15); do
    sleep 1
    # tinyproxy writes its PID file after forking
    if [ -f "$PID_FILE" ]; then
        TPID=$(cat "$PID_FILE" 2>/dev/null)
        [ -n "$TPID" ] && [ -d "/proc/$TPID" ] && break
    fi
    # Fallback: scan /proc directly
    for p in $(ls /proc/ | grep -E "^[0-9]+$"); do
        cmdline=$(cat /proc/$p/cmdline 2>/dev/null | tr '\0' ' ')
        case "$cmdline" in
            */cache/bin/tinyproxy*) TPID=$p; break 2 ;;
        esac
    done
    printf "    %ds...\r" "$i"
done
echo ""

if [ -z "$TPID" ] || [ ! -d "/proc/$TPID" ]; then
    err "tinyproxy did not start within 15s"
    err "Check log: cat $LOG_FILE"
    info "Restoring /etc/inittab..."
    cp "$INITTAB_BAK" "$INITTAB"
    kill -HUP 1
    exit 1
fi

ok "tinyproxy running, PID=$TPID"
grep CapEff /proc/$TPID/status 2>/dev/null | awk '{printf "  [+] CapEff: %s\n", $2}'

# -------------------------------------------------------------------------
# [7] Verify port is listening
# -------------------------------------------------------------------------
hdr "7. Verifying port $PORT"

sleep 1
if netstat -tlnp 2>/dev/null | grep -q ":${PORT}"; then
    ok "Port $PORT is listening"
    netstat -tlnp 2>/dev/null | grep ":${PORT}" | sed 's/^/      /'
else
    info "netstat unavailable — checking /proc/net/tcp..."
    HEX_PORT=$(printf "%04X" "$PORT")
    if grep -qi "$HEX_PORT" /proc/net/tcp 2>/dev/null; then
        ok "Port $PORT confirmed in /proc/net/tcp (hex: $HEX_PORT)"
    else
        info "Could not confirm port via /proc/net/tcp — tinyproxy may still be binding"
    fi
fi

# Show log tail
if [ -f "$LOG_FILE" ]; then
    echo ""
    info "Log tail:"
    tail -8 "$LOG_FILE" 2>/dev/null | sed 's/^/      /'
fi

# -------------------------------------------------------------------------
# [8] Restore /etc/inittab
# -------------------------------------------------------------------------
hdr "8. Restoring /etc/inittab"

grep -v "^${TAG}" "$INITTAB" > /data/tmp/inittab.tprox.clean 2>/dev/null
cp /data/tmp/inittab.tprox.clean "$INITTAB"
rm -f /data/tmp/inittab.tprox.clean
kill -HUP 1
ok "inittab restored and init signaled"

# -------------------------------------------------------------------------
# [9] Cleanup staging directory
# -------------------------------------------------------------------------
hdr "9. Cleanup"

rm -rf "$SRC_DIR"
ok "Removed staging directory: $SRC_DIR"

# -------------------------------------------------------------------------
# Done
# -------------------------------------------------------------------------
echo ""
echo "========================================"
echo " INSTALL COMPLETE"
echo "========================================"
echo ""
echo " Binary  : $TINYPROXY_BIN"
echo " Config  : $CONF_FILE"
echo " Log     : $LOG_FILE"
echo " PID     : $PID_FILE (PID=$TPID)"
echo ""
echo " PROXY SETTINGS FOR WIFI CLIENTS:"
echo "   HTTP Proxy:  $LISTEN_IP"
echo "   Port:        $PORT"
echo "   (works for HTTP and HTTPS via CONNECT tunnel)"
echo ""
echo " MANAGE:"
echo "   Stop:    kill \$(cat $PID_FILE)"
echo "   Log:     cat $LOG_FILE"
echo "   Config:  cat $CONF_FILE"
echo ""
echo " TRANSPARENT HTTP REDIRECT (optional, requires xtables daemon):"
echo "   sh /cache/ipt/ipt_ctl.sh iptables -t nat -A ORBIC_PREROUTING \\"
echo "       -i bridge0 -p tcp --dport 80 ! -d $LISTEN_IP \\"
echo "       -j REDIRECT --to-ports $PORT"
echo "   Note: only intercepts HTTP (port 80). HTTPS requires client config."
echo ""
echo " TO RESTART after reboot or kill:"
echo "   Re-push from PC and re-run this script, OR"
echo "   add a 'respawn' inittab entry for persistent service."
echo ""
